#!/bin/bash

if [[ "x$DOCKINGSTATION" -eq "x" ]]; then
	echo "Please set the DOCKINGSTATION environment varaible and run again"
	exit
fi

echo "Installing docker & friends..."

# install docker on the base image
curl -L https://raw.github.com/cthulhuology/ubuntu-to-docker/master/setup.sh | bash

# test if docker works
docker ps

# if not run again because why not!
if [[ $? ]]; then
	curl -L https://raw.github.com/cthulhuology/ubuntu-to-docker/master/setup.sh | bash
fi

# install the dockingbay service which will contact the docking station
curl -L https://raw.github.com/cthulhuology/dockingclamps/master/bin/dockingbay > /usr/sbin/dockingbay
chmod 555 /usr/sbin/dockingbay

# symlink as a service and enable on boot
ln -s /usr/sbin/dockingbay /etc/init.d/dockingbay
update-rc.d dockingbay enable

# configure the docking station for this image
echo "Configuring for dockingstation $DOCKINGSTATION"
mkdir -p /etc/dockingclamps/
echo "DOCKINGSTATION=$DOCKINGSTATION" > /etc/dockingclamps/station
